### ISSUE TITLE
Htmltags.ToPrettyString

### ISSUE THREAD

**Issue by ciclerou** [HtmlTags/htmltags#103]
I am updating an app that uses HtmlTags.ToPrettyString, but I had 3.0.0.186 and updated to 7.0.3 and this tag isn't there.  Is there a replacement tag for this old one?

**Comment by jbogard** [comment]
I couldn’t get it to translate over easily unfortunately.

**Comment by jbogard** [comment]
I removed it because I had removed the usage of [https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.htmltextwriter?view=netframework-4.8](HtmlTextWriter) which does not exist in ASP.NET Core. I had to completely take over writing out the HTML, and adding this additional functionality would have been too much to take on.
